language: ruby
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - 2.3.1
  - ruby-head
  - rbx-2
before_install:
  - gem install bundler
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-2
  fast_finish: true
