language: ruby
rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3.4
  - 2.4.1
  - ruby-head
before_install:
  - gem install bundler
matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
before_install: gem install bundler -v 1.14.6
